up again

diff --git a/.github/workflows/automaticdeploy.yml b/.github/workflows/automaticdeploy.yml
--- a/.github/workflows/automaticdeploy.yml
+++ b/.github/workflows/automaticdeploy.yml
@@ -19,6 +19,23 @@ jobs:
           port: ${{ secrets.SSH_PORT }}
           script: |
             cd ~/../aryanattapt/btbschool-fe
-            git pull origin master
-            docker stop btbschool-fe && docker compose up --build --force-recreate 
-            docker restart aryanattapt-nginx
+            if ! git pull origin master; then
+              echo "Git pull failed. exit the process..."
+              exit 1;
+            fi
+            
+            if ! docker stop btbschool-fe; then
+              echo "btbschool-fe stop failed. continue process..."
+            fi
+
+            if ! docker system prune -af; then
+              echo "btbschool-fe clean up failed. continue process..."
+            fi
+            
+            if ! docker compose up -d; then
+              echo "btbschool-fe build up failed. continue process..."
+            fi
+            
+            if ! docker restart aryanattapt-nginx; then
+              echo "nginx restart failed"
+            fi
