disable script

diff --git a/.github/workflows/automaticdeploy.yml b/.github/workflows/automaticdeploy.yml
--- a/.github/workflows/automaticdeploy.yml
+++ b/.github/workflows/automaticdeploy.yml
@@ -1,46 +1,46 @@
-name: automaticdeploy
+# name: automaticdeploy
 
-on:
-  push:
-    branches:
-      - master
+# on:
+#   push:
+#     branches:
+#       - master
 
-jobs:
-  automaticdeploy:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Automatic Deployment
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          password: ${{ secrets.SSH_PASSWORD }}
-          port: ${{ secrets.SSH_PORT }}
-          script: |
-            cd ~/../aryanattapt/btbschool-fe
-            if ! git reset --hard; then
-              echo "Git reset failed. Exiting process..."
-              exit 1;
-            fi
+# jobs:
+#   automaticdeploy:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@v2
+#       - name: Automatic Deployment
+#         uses: appleboy/ssh-action@master
+#         with:
+#           host: ${{ secrets.SSH_HOST }}
+#           username: ${{ secrets.SSH_USERNAME }}
+#           password: ${{ secrets.SSH_PASSWORD }}
+#           port: ${{ secrets.SSH_PORT }}
+#           script: |
+#             cd ~/../aryanattapt/btbschool-fe
+#             if ! git reset --hard; then
+#               echo "Git reset failed. Exiting process..."
+#               exit 1;
+#             fi
 
-            if ! git pull origin master; then
-              echo "Git pull failed. exit the process..."
-              exit 1;
-            fi
+#             if ! git pull origin master; then
+#               echo "Git pull failed. exit the process..."
+#               exit 1;
+#             fi
             
-            if ! docker stop btbschool-fe; then
-              echo "btbschool-fe stop failed. continue process..."
-            fi
+#             if ! docker stop btbschool-fe; then
+#               echo "btbschool-fe stop failed. continue process..."
+#             fi
 
-            if ! docker system prune -af; then
-              echo "btbschool-fe clean up failed. continue process..."
-            fi
+#             if ! docker system prune -af; then
+#               echo "btbschool-fe clean up failed. continue process..."
+#             fi
             
-            if ! docker compose up -d; then
-              echo "btbschool-fe build up failed. continue process..."
-            fi
+#             if ! docker compose up -d; then
+#               echo "btbschool-fe build up failed. continue process..."
+#             fi
             
-            if ! docker restart aryanattapt-nginx; then
-              echo "nginx restart failed"
-            fi
+#             if ! docker restart aryanattapt-nginx; then
+#               echo "nginx restart failed"
+#             fi
